.binstar.yml, conda.recipe/bld.bat, conda.recipe/build.sh, conda.recipe/meta.yaml, conda.recipe/post-link.bat, conda.recipe/post-link.sh, conda.recipe/pre-unlink.bat, conda.recipe/pre-unlink.sh, nb_conda_kernels/__init__.py, nb_conda_kernels/_version.py, nb_conda_kernels/install.py, nb_conda_kernels/nb_conda_kernels.py, setup.py
Create a custom KernelSpecManager able to read conda envs and create kernelspecs for them. Also all the packaging.
This is tied to this PR https://github.com/Anaconda-Server/anaconda-notebook/pull/107, which removes leftovers.
=> CondaKernelSpecManager (aka, reinterpretation of syncer)

nb_conda_kernels/manager.py, nb_conda_kernels/tests/test_api.py, nb_conda_kernels/tests/test_notebook.py, package.json
This adds:
- caching of `conda info` and the generated kernelspecs (this was really slow!). Default for a minute.
- tests for bad conda (not on path or something)
I've bumped to 2.0, as once this is mergeable, we should be good to go.
I started looking at the complexities entailed in the other extensions, but for now have just created some placeholders:
- https://github.com/Anaconda-Platform/nb_conda/issues/27
- https://github.com/Anaconda-Platform/nb_anacondacloud/issues/30
=> More robust handling of conda info, bad conda

nb_conda_kernels/manager.py
In some deployments, there may be conda environments present that
should not appear in the list (e.g., environments that may have
jupyter, python, R but not kernels)
=> Support CondaKernelSpecManager.env_filter regex

nb_conda_kernels/tests/test_api.py, nb_conda_kernels/tests/test_notebook.py
Essentially disabling token auth for testing so casper an friends can do the job. Also skippping some test in the API because right now the parent class disable extension by default, so nb_conda_kernels is not available. This probably need a fix or config option upstream.
=> Some fixes related with the CI machinery

.gitignore, .travis.yml, README.md, appveyor.yml, conda-recipe/meta.yaml, conda-recipe/post-link.bat, conda-recipe/post-link.sh, conda-recipe/pre-unlink.bat, conda-recipe/pre-unlink.sh, conda-recipe/run_test.bat, conda-recipe/run_test.py, conda-recipe/run_test.sh, nb_conda_kernels/_version.py, nb_conda_kernels/install.py, nb_conda_kernels/manager.py, package.json, setup.cfg
Currently conda-forge is being used to build things. There's nothing wrong with that _per se_. But because the conda package requires post-link and pre-unlink scripts to work properly, they should be part of the source, and included here.
To that end I've pulled those scripts over and a basic conda recipe that builds the package locally. Nothing has been changed w.r.t. the current AppVeyor/Travis builds, but in theory, these should be building and testing the conda packages to fully vet the post-link/pre-unlink scripts.
Future work:
- More testing in the conda build process itself
- Modify appveyor and travis scripts to use the recipe
=> Add conda 4.4 support; move to conda-based testing

nb_conda_kernels/manager.py
If `env_filter` is specified the kernel was not process correctly. This corrects it.
=> BUG if cascade breaking if env_filter is set

README.md, nb_conda_kernels/manager.py, nb_conda_kernels/tests/js/test_notebook_root_py.js
Allow user to customize display name through configuration:
```json
"CondaKernelSpecManager": {
"name_format": "{0}-{1}"
}
```
The argument *0* is the language and the *1* is the environment name.
=> Customize display name

.travis.yml, appveyor.yml
The `jupycon` organization has been created to hold both development and tagged release builds of `nb_conda_kernels` and the other Jupyter/Conda packages.
=> Upload packages to Anaconda Cloud

README.md, conda-recipe/post-link.bat, conda-recipe/post-link.sh, conda-recipe/pre-unlink.bat, conda-recipe/pre-unlink.sh, nb_conda_kernels/install.py, nb_conda_kernels/tests/test_install.py
Installs into `sys.prefix` by default, generally making the need to supply a `--prefix` argument irrelevant. Also adds additional checks to make sure the enabling/disabling isn't thwarted by configurations outside of sys.prefix (e.g., `~/.jupyter`, `/etc/jupyter`)
=> Harden install script

.travis.yml, nb_conda_kernels/manager.py, nb_conda_kernels/tests/test_config.py, nb_conda_kernels/tests/test_runner.py
Fixes #113. Doesn't skip `sys.prefix` when listing conda-based kernels; adds ` *` to the display name of that environment to indicate that's the currently running environment.
=> Put back default environment into conda env list

.travis.yml, appveyor.yml, conda-recipe/testenv2.yaml, nb_conda_kernels/tests/test_config.py
Newer versions of conda have stopped allowing spaces in environment names. We were deliberately testing that case here so now our scripts are broken. For now let's declare victory and move on, by removing that test.
=> Remove space in test environment

conda-recipe/post-link.bat, conda-recipe/post-link.sh, conda-recipe/pre-unlink.bat, conda-recipe/pre-unlink.sh
Explicitly Pass "--prefix", the default should be fine but it is safer to be
explicit.
Simplify the scripts by removing the block, they are un-needed for single line
commands.
In the windows scripts set the PATH explicitly as most versions of conda do not
set this prior to calling the script. See:
https://github.com/conda/conda/issues/7789
=> enhance conda post-link and pre-unlink scripts

.travis.yml, appveyor.yml, conda-recipe/meta.yaml, nb_conda_kernels/manager.py, nb_conda_kernels/tests/test_config.py
This patch adds an extra identifier to any kernel name that lives in an environment outside of `$_CONDA_ROOT/envs`. For instance, if the environment is built within an Anaconda Project, this will be the project name. If the environment is built within an alternate conda installation, this will be the directory name of that installation.
=> Add project name to kernel name

nb_conda_kernels/runner.py
Significant simplification of the runner script. Should be faster and more reliable. Not guaranteed to work outside of the `nb_conda_kernels` context.
=> Simplify runner

README.md
Correct brackets balance in the README to have a correct snippet for user to copy-paste.
=> Correct config snippet

nb_conda_kernels/install.py, tests/test_install.py
Even though I cannot reproduce #158 I am concerned that our recent switch to using `JupyterApp` instead of `NotebookApp`, and `jupyter_config.json` instead of `jupyter_notebook_config.json`, might be leading to issues upon upgrade or uninstall/reinstall.
To that end I've modified the code for install to do a lot of cleanup when possible, and to better interpret the config landscape. In particular, it removes any extraneous configurations using the `NotebookApp` class or the older file location. And when looking at the effective status, it considers all of these potential values in the global configuration directories, too.
=> Improve the installation mechanism

nb_conda_kernels/manager.py, nb_conda_kernels/runner.py, tests/conftest.py, tests/test_runner.py
Fixes #183
This add `RUNNER_COMMAND` to all exported kernelspecs. But it changes the runner to activate the environment only if it is not matching `sys.prefix`.
I added some unit tests for it - but bypass the unicode named kernel on Linux as it brought an error not related to `nb_conda_kernels` code.
=> Use RUNNER_COMMAND for all exported kernelspecs

README.md, nb_conda_kernels/manager.py, tests/test_config.py
The naming options available does not allow to distinguish some kernels. In particular if you install `ipykernel` and `xpython` in the same conda environment, they will have identical _Language_ and _Environment name_.
This PR extends the field names available for `name_format` while ensuring backward compatibility and maintaining the default name.
`name_format`: String name format  
Default: `'{language} [conda env:{environment}]'`  
Available field names within the string:
- `{0}` = Language
- `{1}` = Environment name
- `{conda_kernel}` = Dynamically built kernel name for conda environment
- `{display_name}` = Kernel displayed name (as defined in the kernel spec)
- `{environment}`  = Environment name (identical to `{1}`)
- `{kernel}` = Original kernel name (name of the folder containing …
=> Offer more option for displayed kernel name

nb_conda_kernels/manager.py, requirements.txt, testbed/testenv1.yaml, tests/test_runner.py
When running conda info, the process spawns some child process and doesnt wait for them before exiting. This causes the child processes to reach an unreapable zombie state in some environments. Continued use means that these zombie process can accumulate quite quickly.
Includes a small fix to test, python2 no longer supported by ipykernel
=> Zombie processes

.github/workflows/main.yml
upload-artifact@v4 no longer supports the merge behavior that our GHA structure relies on. Until this can be fixed we must stick with v3
=> revert to upload-artifact@v3

.github/workflows/main.yml, conda-recipe/meta.yaml
Fixes #244 
The packages are built on unix and windows, but tested on windows, mac, and linux. Uses the same technique as @mathause used here: https://github.com/conda-forge/nb_conda_kernels-feedstock/pull/52
So we're actually testing the build framework that conda-forge is trying to move to.
=> split windows/unix noarch

.github/workflows/main.yml, conda-recipe/meta.yaml, nb_conda_kernels/install.py, nb_conda_kernels/manager.py, tests/test_api.py
Fixes #223 
Also makes the log output look closer to what other extensions use
=> use ServerApp / NotebookApp instead of JupyterApp

nb_conda_kernels/manager.py, tests/test_config.py
Fixes #225
Fixes #218 
- Deduplicates the kernel set, preferring the nb_conda_kernels entry over the original.
- Properly handles case-sensitive filesystems now
- changed the term used to refer to the top-level environment from `root` to `base`, following modern conda standards. For users who are accustomed to the old use of `root`, I created a new configuration value `base_name`.
=> properly handle case sensitivity; deduplicate

README.md, nb_conda_kernels/manager.py, tests/test_config.py
A new configuration parameter is added `enable_debugger`. If left off the debugger metadata value is taken from the source kernelspec in the conda environment. When set `enable_debugger` will override the value. This is was tested on jupyterlab 4 with a standard python (not xpython) kernel.
=> enable the debugger

nb_conda_kernels/manager.py
Closes https://github.com/Anaconda-Platform/nb_conda_kernels/issues/261
Exposes the following metadata in the kernel specs:
- `language`
- `raw_kernel_name`
- `is_base_environment`
- `is_currently_running`
To allow for rich display/formatting on the frontend.
Each metadata entry is prefixed with `conda_` to avoid conflicts with other metadata keys. I am happy to adjust the prefix but this appears sensible to me.
=> Expose additional metadata to kernelspecs

.github/workflows/main.yml, conda-recipe/meta.yaml, tests/test_config.py
At least one of the tests requires the existence of the testbed. But we'd like to be able to run as many tests as possible from within the conda build itself. To that end I'm marking testbed-dependent tests with `pytest.mark.testbed`.
The two tests are:
- `test_config.py/test_configuration`: this test is designed to verify that the testbed contains a proper mix of kernel installation scenarios.
- `test_config.py/test_install_kernelspec`: this test will fail unless there is at least one kernel installed outside of the conda-build environment.
Because the CI _does_ exercise these tests fully, we are safe to skip them in the recipe build.
In order to test this, we've removed the `--no-test` option in the `build` stage.
=> Skip the tests that only work with the testbed
